---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u4753695/public_html/
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
